package com.example.suicareader.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage { EN, ZH, JA }

data class AppStrings(
    val appName: String,
    val dashboardTitle: String,
    val settingsTitle: String,
    val darkTheme: String,
    val darkThemeDesc: String,
    val language: String,
    val languageDesc: String,
    val openSource: String,
    val openSourceDesc: String,
    val addManualEntry: String,
    val typeFare: String,
    val typeCharge: String,
    val amountInput: String,
    val selectInStation: String,
    val selectOutStation: String,
    val cancel: String,
    val save: String,
    val searchStation: String,
    val searchPlaceholder: String,
    val noResults: String,
    val fareSubway: String,
    val chargeTopUp: String,
    val busFare: String,
    val purchase: String,
    val locationPrefix: String,
    val busRoutePrefix: String,
    val terminalPrefix: String,
    val inPrefix: String,
    val outPrefix: String,
    val currentBalance: String,
    val editCard: String,
    val renameCard: String,
    val deleteCard: String,
    val renameDialogTitle: String,
    val cardNameLabel: String,
    val cardNumberLabel: String,
    val cardNumberPlaceholder: String,
    val tripHistory: String,
    val balanceLabel: String,
    val dateLabel: String,
    val timeLabel: String,
    val typeLabel: String,
    val tripNameLabel: String,
    val noteLabel: String,
    val mapPreviewComingSoon: String,
    val tripNotFound: String,
    val noNote: String,
    val editTrip: String,
    val chooseType: String,
    val typeTrain: String,
    val typeBus: String,
    val typeRecharge: String,
    val typeLocker: String,
    val typeExpense: String,
    val back: String,
    val start: String,
    val end: String,
    val amountLabel: String,
    val rawBlockLabel: String,
    val transactionLabel: String,
    val unknownCard: String,
    val lockerUsage: String,
    val cardOptionsTitle: String,
    val deleteCardTitle: String,
    val deleteCardMessage: String,
    val tripOptionsTitle: String,
    val editTripOption: String,
    val deleteTripOption: String,
    val deleteTripTitle: String,
    val deleteTripMessage: String,
    val inShortLabel: String,
    val outShortLabel: String,
    val busShortLabel: String,
    val locationShortLabel: String,
    val selectBusCompany: String,
    val selectRechargeStation: String,
    val allLabel: String,
    val selectBusCompanyTitle: String
)

val EnStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "My Cards",
    settingsTitle = "Settings",
    darkTheme = "Dark Theme",
    darkThemeDesc = "Toggle liquid glass background mode",
    language = "Language",
    languageDesc = "System Default / Selected",
    openSource = "Open Source",
    openSourceDesc = "View GitHub Repository",
    addManualEntry = "Add Manual Entry",
    typeFare = "Fare",
    typeCharge = "Charge",
    amountInput = "Amount (¥)",
    selectInStation = "Select In-Station / Location",
    selectOutStation = "Select Out-Station",
    cancel = "Cancel",
    save = "Save",
    searchStation = "Search Station",
    searchPlaceholder = "Enter station name...",
    noResults = "No results found.",
    fareSubway = "Fare (Subway)",
    chargeTopUp = "Charge (Top-up)",
    busFare = "Bus Fare",
    purchase = "Purchase (Vending/Store)",
    locationPrefix = "Location:",
    busRoutePrefix = "Bus Route/ID:",
    terminalPrefix = "Terminal:",
    inPrefix = "In:",
    outPrefix = "Out:",
    currentBalance = "Current Balance",
    editCard = "Edit Card",
    renameCard = "Rename",
    deleteCard = "Delete",
    renameDialogTitle = "Rename Card",
    cardNameLabel = "Card Name",
    cardNumberLabel = "Card Number (Last 4 digits)",
    cardNumberPlaceholder = "Optional",
    tripHistory = "Trip History",
    balanceLabel = "Balance",
    dateLabel = "Date",
    timeLabel = "Time",
    typeLabel = "Type",
    tripNameLabel = "Trip Name",
    noteLabel = "Note",
    mapPreviewComingSoon = "Map Preview",
    tripNotFound = "Trip not found",
    noNote = "No note",
    editTrip = "Edit Trip",
    chooseType = "Choose Type",
    typeTrain = "Train",
    typeBus = "Bus",
    typeRecharge = "Recharge",
    typeLocker = "Locker",
    typeExpense = "Expense",
    back = "Back",
    start = "Start",
    end = "End",
    amountLabel = "Amount",
    rawBlockLabel = "Raw Block",
    transactionLabel = "Transaction",
    unknownCard = "Unknown Card",
    lockerUsage = "Locker usage",
    cardOptionsTitle = "Card Options",
    deleteCardTitle = "Delete Card?",
    deleteCardMessage = "This will permanently delete the card and all its trip history. This action cannot be undone.",
    tripOptionsTitle = "Trip Options",
    editTripOption = "Edit Trip",
    deleteTripOption = "Delete Trip",
    deleteTripTitle = "Delete Trip?",
    deleteTripMessage = "This will permanently delete this trip record. This action cannot be undone.",
    inShortLabel = "In:",
    outShortLabel = "Out:",
    busShortLabel = "Bus:",
    locationShortLabel = "Location:",
    selectBusCompany = "Select Bus Company",
    selectRechargeStation = "Select Recharge Station",
    allLabel = "All",
    selectBusCompanyTitle = "Select Bus Company"
)

val ZhStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "我的卡片",
    settingsTitle = "设置",
    darkTheme = "深色模式",
    darkThemeDesc = "切换深色液态玻璃背景",
    language = "语言",
    languageDesc = "系统默认 / 已选择",
    openSource = "开源项目",
    openSourceDesc = "查看 GitHub 仓库",
    addManualEntry = "手动记账",
    typeFare = "乘车/消费",
    typeCharge = "充值",
    amountInput = "金额 (¥)",
    selectInStation = "选择进站 / 发生地",
    selectOutStation = "选择出站",
    cancel = "取消",
    save = "保存",
    searchStation = "搜索车站",
    searchPlaceholder = "输入车站拼音或汉字...",
    noResults = "未找到结果",
    fareSubway = "地铁/电车",
    chargeTopUp = "充值",
    busFare = "公交",
    purchase = "购物/自动售货机",
    locationPrefix = "地点:",
    busRoutePrefix = "公交线路:",
    terminalPrefix = "终端:",
    inPrefix = "进:",
    outPrefix = "出:",
    currentBalance = "当前余额",
    editCard = "编辑卡片",
    renameCard = "重命名",
    deleteCard = "删除",
    renameDialogTitle = "修改卡片信息",
    cardNameLabel = "卡片名称",
    cardNumberLabel = "卡号尾数 (后四位)",
    cardNumberPlaceholder = "选填",
    tripHistory = "行程记录",
    balanceLabel = "余额",
    dateLabel = "日期",
    timeLabel = "时间",
    typeLabel = "类型",
    tripNameLabel = "行程名称",
    noteLabel = "备注",
    mapPreviewComingSoon = "地图预览",
    tripNotFound = "未找到行程",
    noNote = "暂无备注",
    editTrip = "编辑行程",
    chooseType = "选择类型",
    typeTrain = "轨道交通",
    typeBus = "公交",
    typeRecharge = "充值",
    typeLocker = "储物柜",
    typeExpense = "消费",
    back = "返回",
    start = "起点",
    end = "终点",
    amountLabel = "金额",
    rawBlockLabel = "原始区块",
    transactionLabel = "交易",
    unknownCard = "未知卡片",
    lockerUsage = "储物柜使用",
    cardOptionsTitle = "卡片选项",
    deleteCardTitle = "删除卡片？",
    deleteCardMessage = "此操作将永久删除该卡片及其所有行程记录，且无法撤销。",
    tripOptionsTitle = "行程选项",
    editTripOption = "编辑行程",
    deleteTripOption = "删除行程",
    deleteTripTitle = "删除行程？",
    deleteTripMessage = "此操作将永久删除该行程记录，且无法撤销。",
    inShortLabel = "进:",
    outShortLabel = "出:",
    busShortLabel = "公交:",
    locationShortLabel = "地点:",
    selectBusCompany = "选择公交公司",
    selectRechargeStation = "选择充值车站",
    allLabel = "全部",
    selectBusCompanyTitle = "选择公交公司"
)

val JaStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "マイカード",
    settingsTitle = "設定",
    darkTheme = "ダークモード",
    darkThemeDesc = "液体ガラスの背景を切り替え",
    language = "言語",
    languageDesc = "システムデフォルト / 選択済み",
    openSource = "オープンソース",
    openSourceDesc = "GitHub リポジトリを表示",
    addManualEntry = "手動入力",
    typeFare = "運賃/支払い",
    typeCharge = "チャージ",
    amountInput = "金額 (¥)",
    selectInStation = "乗車駅 / 場所を選択",
    selectOutStation = "降車駅を選択",
    cancel = "キャンセル",
    save = "保存",
    searchStation = "駅を検索",
    searchPlaceholder = "駅名を入力...",
    noResults = "結果が見つかりません",
    fareSubway = "運賃 (電車)",
    chargeTopUp = "チャージ",
    busFare = "バス運賃",
    purchase = "物販",
    locationPrefix = "場所:",
    busRoutePrefix = "バス路線:",
    terminalPrefix = "端末:",
    inPrefix = "入:",
    outPrefix = "出:",
    currentBalance = "残高",
    editCard = "カードを編集",
    renameCard = "名前を変更",
    deleteCard = "削除",
    renameDialogTitle = "カード情報の編集",
    cardNameLabel = "カード名",
    cardNumberLabel = "カード番号 (下4桁)",
    cardNumberPlaceholder = "任意",
    tripHistory = "利用履歴",
    balanceLabel = "残高",
    dateLabel = "日付",
    timeLabel = "時刻",
    typeLabel = "種別",
    tripNameLabel = "履歴名",
    noteLabel = "メモ",
    mapPreviewComingSoon = "マップ表示",
    tripNotFound = "履歴が見つかりません",
    noNote = "メモなし",
    editTrip = "履歴を編集",
    chooseType = "種別を選択",
    typeTrain = "鉄道",
    typeBus = "バス",
    typeRecharge = "チャージ",
    typeLocker = "ロッカー",
    typeExpense = "支出",
    back = "戻る",
    start = "開始",
    end = "終了",
    amountLabel = "金額",
    rawBlockLabel = "Raw Block",
    transactionLabel = "取引",
    unknownCard = "不明なカード",
    lockerUsage = "ロッカー利用",
    cardOptionsTitle = "カードオプション",
    deleteCardTitle = "カードを削除しますか？",
    deleteCardMessage = "このカードと利用履歴はすべて完全に削除されます。この操作は元に戻せません。",
    tripOptionsTitle = "履歴オプション",
    editTripOption = "履歴を編集",
    deleteTripOption = "履歴を削除",
    deleteTripTitle = "履歴を削除しますか？",
    deleteTripMessage = "この履歴は完全に削除されます。この操作は元に戻せません。",
    inShortLabel = "入:",
    outShortLabel = "出:",
    busShortLabel = "バス:",
    locationShortLabel = "場所:",
    selectBusCompany = "バス会社を選択",
    selectRechargeStation = "チャージ駅を選択",
    allLabel = "すべて",
    selectBusCompanyTitle = "バス会社を選択"
)

val LocalStrings = staticCompositionLocalOf { EnStrings }

val LocalTextColor = staticCompositionLocalOf { androidx.compose.ui.graphics.Color.White }
