package com.example.suicareader.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage { EN, ZH, JA }

data class AppStrings(
    val appName: String,
    val dashboardTitle: String,
    val settingsTitle: String,
    val darkTheme: String,
    val darkThemeDesc: String,
    val language: String,
    val languageDesc: String,
    val openSource: String,
    val openSourceDesc: String,
    val addManualEntry: String,
    val typeFare: String,
    val typeCharge: String,
    val amountInput: String,
    val selectInStation: String,
    val selectOutStation: String,
    val cancel: String,
    val save: String,
    val searchStation: String,
    val searchPlaceholder: String,
    val noResults: String,
    val fareSubway: String,
    val chargeTopUp: String,
    val busFare: String,
    val purchase: String,
    val locationPrefix: String,
    val busRoutePrefix: String,
    val terminalPrefix: String,
    val inPrefix: String,
    val outPrefix: String,
    val currentBalance: String,
    val editCard: String,
    val renameCard: String,
    val deleteCard: String,
    val renameDialogTitle: String,
    val cardNameLabel: String,
    val cardNumberLabel: String,
    val cardNumberPlaceholder: String,
    val tripHistory: String,
    val balanceLabel: String,
    val dateLabel: String,
    val timeLabel: String,
    val typeLabel: String,
    val tripNameLabel: String,
    val noteLabel: String,
    val mapPreviewComingSoon: String,
    val tripNotFound: String,
    val noNote: String,
    val editTrip: String,
    val chooseType: String,
    val typeTrain: String,
    val typeBus: String,
    val typeRecharge: String,
    val typeLocker: String,
    val typeExpense: String,
    val back: String,
    val start: String,
    val end: String,
    val amountLabel: String,
    val amountInputHint: String,
    val dateInputHint: String,
    val pickDate: String,
    val invalidDateMessage: String,
    val invalidAmountMessage: String,
    val rawBlockLabel: String,
    val transactionLabel: String,
    val unknownCard: String,
    val lockerUsage: String,
    val cardOptionsTitle: String,
    val deleteCardTitle: String,
    val deleteCardMessage: String,
    val tripOptionsTitle: String,
    val editTripOption: String,
    val deleteTripOption: String,
    val deleteTripTitle: String,
    val deleteTripMessage: String,
    val inShortLabel: String,
    val outShortLabel: String,
    val busShortLabel: String,
    val locationShortLabel: String,
    val selectBusCompany: String,
    val selectRechargeStation: String,
    val allLabel: String,
    val selectBusCompanyTitle: String,
    val importExportTitle: String,
    val importTrips: String,
    val exportCurrentTrips: String,
    val tripExportSuccess: String,
    val tripExportFailed: String,
    val tripImportInvalid: String,
    val tripImportSuccess: String,
    val tripImportFailed: String,
    val popularStations: String,
    val selectRailCompany: String,
    val noneLabel: String,
    val lastUpdatedLabel: String,
    val tripCapacityHint: String,
    val journeyTitle: String,
    val journeyBetaTitle: String,
    val journeyBetaDesc: String,
    val journeyFilterCards: String,
    val journeyNationwide: String,
    val journeyModeRoutes: String,
    val journeyModeCompanies: String,
    val journeyTopCardTitle: String,
    val journeyTopCardSubtitle: String,
    val cityTokyo: String,
    val cityOsaka: String,
    val cityKyoto: String,
    val cityYokohama: String,
    val cityNagoya: String,
    val cityFukuoka: String,
    val cityOther: String
)

val EnStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "My Cards",
    settingsTitle = "Settings",
    darkTheme = "Dark Theme",
    darkThemeDesc = "Toggle liquid glass background mode",
    language = "Language",
    languageDesc = "System Default / Selected",
    openSource = "Open Source",
    openSourceDesc = "View GitHub Repository",
    addManualEntry = "Add Manual Entry",
    typeFare = "Fare",
    typeCharge = "Charge",
    amountInput = "Amount (¥)",
    selectInStation = "Select In-Station / Location",
    selectOutStation = "Select Out-Station",
    cancel = "Cancel",
    save = "Save",
    searchStation = "Search Station",
    searchPlaceholder = "Enter station name...",
    noResults = "No results found.",
    fareSubway = "Fare (Subway)",
    chargeTopUp = "Charge (Top-up)",
    busFare = "Bus Fare",
    purchase = "Purchase (Vending/Store)",
    locationPrefix = "Location:",
    busRoutePrefix = "Bus Route/ID:",
    terminalPrefix = "Terminal:",
    inPrefix = "In:",
    outPrefix = "Out:",
    currentBalance = "Current Balance",
    editCard = "Edit Card",
    renameCard = "Rename",
    deleteCard = "Delete",
    renameDialogTitle = "Rename Card",
    cardNameLabel = "Card Name",
    cardNumberLabel = "Card Number (Last 4 digits)",
    cardNumberPlaceholder = "Optional",
    tripHistory = "Trip History",
    balanceLabel = "Balance",
    dateLabel = "Date",
    timeLabel = "Time",
    typeLabel = "Type",
    tripNameLabel = "Trip Name",
    noteLabel = "Note",
    mapPreviewComingSoon = "Map Preview",
    tripNotFound = "Trip not found",
    noNote = "No note",
    editTrip = "Edit Trip",
    chooseType = "Choose Type",
    typeTrain = "Train",
    typeBus = "Bus",
    typeRecharge = "Recharge",
    typeLocker = "Locker",
    typeExpense = "Expense",
    back = "Back",
    start = "Start",
    end = "End",
    amountLabel = "Amount",
    amountInputHint = "Example: -220 or 1000",
    dateInputHint = "Format: yyyy-MM-dd",
    pickDate = "Pick Date",
    invalidDateMessage = "Please enter a valid date in yyyy-MM-dd format",
    invalidAmountMessage = "Please enter a valid integer amount",
    rawBlockLabel = "Raw Block",
    transactionLabel = "Transaction",
    unknownCard = "Unknown Card",
    lockerUsage = "Locker usage",
    cardOptionsTitle = "Card Options",
    deleteCardTitle = "Delete Card?",
    deleteCardMessage = "This will permanently delete the card and all its trip history. This action cannot be undone.",
    tripOptionsTitle = "Trip Options",
    editTripOption = "Edit Trip",
    deleteTripOption = "Delete Trip",
    deleteTripTitle = "Delete Trip?",
    deleteTripMessage = "This will permanently delete this trip record. This action cannot be undone.",
    inShortLabel = "In:",
    outShortLabel = "Out:",
    busShortLabel = "Bus:",
    locationShortLabel = "Location:",
    selectBusCompany = "Select Bus Company",
    selectRechargeStation = "Select Recharge Station",
    allLabel = "All",
    selectBusCompanyTitle = "Select Bus Company",
    importExportTitle = "Import / Export",
    importTrips = "Import trip data",
    exportCurrentTrips = "Export current card trips",
    tripExportSuccess = "Trips exported successfully",
    tripExportFailed = "Trip export failed",
    tripImportInvalid = "Invalid import file",
    tripImportSuccess = "Trips imported successfully, balance recalculated",
    tripImportFailed = "Trip import failed",
    popularStations = "Popular stations",
    selectRailCompany = "Select rail company (or skip)",
    noneLabel = "None",
    lastUpdatedLabel = "Last updated",
    tripCapacityHint = "The card stores up to 20 trips, please update in time.",
    journeyTitle = "Journey",
    journeyBetaTitle = "Journey (Beta)",
    journeyBetaDesc = "Enable experimental journey features",
    journeyFilterCards = "Filter cards",
    journeyNationwide = "Nationwide",
    journeyModeRoutes = "Rail Routes",
    journeyModeCompanies = "Rail Companies",
    journeyTopCardTitle = "Top 3",
    journeyTopCardSubtitle = "Top Cities",
    cityTokyo = "Tokyo",
    cityOsaka = "Osaka",
    cityKyoto = "Kyoto",
    cityYokohama = "Yokohama",
    cityNagoya = "Nagoya",
    cityFukuoka = "Fukuoka",
    cityOther = "Other"
)

val ZhStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "我的卡片",
    settingsTitle = "设置",
    darkTheme = "深色模式",
    darkThemeDesc = "切换深色液态玻璃背景",
    language = "语言",
    languageDesc = "系统默认 / 已选择",
    openSource = "开源项目",
    openSourceDesc = "查看 GitHub 仓库",
    addManualEntry = "手动记账",
    typeFare = "乘车/消费",
    typeCharge = "充值",
    amountInput = "金额 (¥)",
    selectInStation = "选择进站 / 发生地",
    selectOutStation = "选择出站",
    cancel = "取消",
    save = "保存",
    searchStation = "搜索车站",
    searchPlaceholder = "输入车站拼音或汉字...",
    noResults = "未找到结果",
    fareSubway = "地铁/电车",
    chargeTopUp = "充值",
    busFare = "公交",
    purchase = "购物/自动售货机",
    locationPrefix = "地点:",
    busRoutePrefix = "公交线路:",
    terminalPrefix = "终端:",
    inPrefix = "进:",
    outPrefix = "出:",
    currentBalance = "当前余额",
    editCard = "编辑卡片",
    renameCard = "重命名",
    deleteCard = "删除",
    renameDialogTitle = "修改卡片信息",
    cardNameLabel = "卡片名称",
    cardNumberLabel = "卡号尾数 (后四位)",
    cardNumberPlaceholder = "选填",
    tripHistory = "行程记录",
    balanceLabel = "余额",
    dateLabel = "日期",
    timeLabel = "时间",
    typeLabel = "类型",
    tripNameLabel = "行程名称",
    noteLabel = "备注",
    mapPreviewComingSoon = "地图预览",
    tripNotFound = "未找到行程",
    noNote = "暂无备注",
    editTrip = "编辑行程",
    chooseType = "选择类型",
    typeTrain = "轨道交通",
    typeBus = "公交",
    typeRecharge = "充值",
    typeLocker = "储物柜",
    typeExpense = "消费",
    back = "返回",
    start = "起点",
    end = "终点",
    amountLabel = "金额",
    amountInputHint = "例如: -220 或 1000",
    dateInputHint = "格式: yyyy-MM-dd",
    pickDate = "选择日期",
    invalidDateMessage = "请输入有效日期，格式为 yyyy-MM-dd",
    invalidAmountMessage = "请输入有效的整数金额",
    rawBlockLabel = "原始区块",
    transactionLabel = "交易",
    unknownCard = "未知卡片",
    lockerUsage = "储物柜使用",
    cardOptionsTitle = "卡片选项",
    deleteCardTitle = "删除卡片？",
    deleteCardMessage = "此操作将永久删除该卡片及其所有行程记录，且无法撤销。",
    tripOptionsTitle = "行程选项",
    editTripOption = "编辑行程",
    deleteTripOption = "删除行程",
    deleteTripTitle = "删除行程？",
    deleteTripMessage = "此操作将永久删除该行程记录，且无法撤销。",
    inShortLabel = "进:",
    outShortLabel = "出:",
    busShortLabel = "公交:",
    locationShortLabel = "地点:",
    selectBusCompany = "选择公交公司",
    selectRechargeStation = "选择充值车站",
    allLabel = "全部",
    selectBusCompanyTitle = "选择公交公司",
    importExportTitle = "导入 / 导出",
    importTrips = "导入行程数据",
    exportCurrentTrips = "导出当前卡片行程",
    tripExportSuccess = "行程导出成功",
    tripExportFailed = "行程导出失败",
    tripImportInvalid = "导入文件无效",
    tripImportSuccess = "行程导入成功，已自动重算余额",
    tripImportFailed = "行程导入失败",
    popularStations = "热门站点",
    selectRailCompany = "请选择铁路公司（或留空）",
    noneLabel = "无",
    lastUpdatedLabel = "上次更新时间",
    tripCapacityHint = "卡内最多存储20条行程数据，请及时更新。",
    journeyTitle = "行迹",
    journeyBetaTitle = "行迹 (Beta)",
    journeyBetaDesc = "启用实验性行迹功能",
    journeyFilterCards = "筛选交通卡",
    journeyNationwide = "全国",
    journeyModeRoutes = "铁路路线",
    journeyModeCompanies = "铁路公司",
    journeyTopCardTitle = "Top 3",
    journeyTopCardSubtitle = "热门城市",
    cityTokyo = "东京",
    cityOsaka = "大阪",
    cityKyoto = "京都",
    cityYokohama = "横滨",
    cityNagoya = "名古屋",
    cityFukuoka = "福冈",
    cityOther = "其他"
)

val JaStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "マイカード",
    settingsTitle = "設定",
    darkTheme = "ダークモード",
    darkThemeDesc = "液体ガラスの背景を切り替え",
    language = "言語",
    languageDesc = "システムデフォルト / 選択済み",
    openSource = "オープンソース",
    openSourceDesc = "GitHub リポジトリを表示",
    addManualEntry = "手動入力",
    typeFare = "運賃/支払い",
    typeCharge = "チャージ",
    amountInput = "金額 (¥)",
    selectInStation = "乗車駅 / 場所を選択",
    selectOutStation = "降車駅を選択",
    cancel = "キャンセル",
    save = "保存",
    searchStation = "駅を検索",
    searchPlaceholder = "駅名を入力...",
    noResults = "結果が見つかりません",
    fareSubway = "運賃 (電車)",
    chargeTopUp = "チャージ",
    busFare = "バス運賃",
    purchase = "物販",
    locationPrefix = "場所:",
    busRoutePrefix = "バス路線:",
    terminalPrefix = "端末:",
    inPrefix = "入:",
    outPrefix = "出:",
    currentBalance = "残高",
    editCard = "カードを編集",
    renameCard = "名前を変更",
    deleteCard = "削除",
    renameDialogTitle = "カード情報の編集",
    cardNameLabel = "カード名",
    cardNumberLabel = "カード番号 (下4桁)",
    cardNumberPlaceholder = "任意",
    tripHistory = "利用履歴",
    balanceLabel = "残高",
    dateLabel = "日付",
    timeLabel = "時刻",
    typeLabel = "種別",
    tripNameLabel = "履歴名",
    noteLabel = "メモ",
    mapPreviewComingSoon = "マップ表示",
    tripNotFound = "履歴が見つかりません",
    noNote = "メモなし",
    editTrip = "履歴を編集",
    chooseType = "種別を選択",
    typeTrain = "鉄道",
    typeBus = "バス",
    typeRecharge = "チャージ",
    typeLocker = "ロッカー",
    typeExpense = "支出",
    back = "戻る",
    start = "開始",
    end = "終了",
    amountLabel = "金額",
    amountInputHint = "例: -220 または 1000",
    dateInputHint = "形式: yyyy-MM-dd",
    pickDate = "日付を選択",
    invalidDateMessage = "yyyy-MM-dd 形式で有効な日付を入力してください",
    invalidAmountMessage = "有効な整数金額を入力してください",
    rawBlockLabel = "Raw Block",
    transactionLabel = "取引",
    unknownCard = "不明なカード",
    lockerUsage = "ロッカー利用",
    cardOptionsTitle = "カードオプション",
    deleteCardTitle = "カードを削除しますか？",
    deleteCardMessage = "このカードと利用履歴はすべて完全に削除されます。この操作は元に戻せません。",
    tripOptionsTitle = "履歴オプション",
    editTripOption = "履歴を編集",
    deleteTripOption = "履歴を削除",
    deleteTripTitle = "履歴を削除しますか？",
    deleteTripMessage = "この履歴は完全に削除されます。この操作は元に戻せません。",
    inShortLabel = "入:",
    outShortLabel = "出:",
    busShortLabel = "バス:",
    locationShortLabel = "場所:",
    selectBusCompany = "バス会社を選択",
    selectRechargeStation = "チャージ駅を選択",
    allLabel = "すべて",
    selectBusCompanyTitle = "バス会社を選択",
    importExportTitle = "インポート / エクスポート",
    importTrips = "履歴データをインポート",
    exportCurrentTrips = "このカードの履歴をエクスポート",
    tripExportSuccess = "履歴のエクスポートに成功しました",
    tripExportFailed = "履歴のエクスポートに失敗しました",
    tripImportInvalid = "インポートファイルが無効です",
    tripImportSuccess = "履歴をインポートし、残高を再計算しました",
    tripImportFailed = "履歴のインポートに失敗しました",
    popularStations = "よく使う駅",
    selectRailCompany = "鉄道会社を選択（未選択可）",
    noneLabel = "なし",
    lastUpdatedLabel = "最終更新",
    tripCapacityHint = "カードには最大20件まで履歴が保存されます。早めに更新してください。",
    journeyTitle = "行跡",
    journeyBetaTitle = "行跡 (Beta)",
    journeyBetaDesc = "実験的な行跡機能を有効化",
    journeyFilterCards = "カードを絞り込む",
    journeyNationwide = "全国",
    journeyModeRoutes = "鉄道路線",
    journeyModeCompanies = "鉄道会社",
    journeyTopCardTitle = "Top 3",
    journeyTopCardSubtitle = "人気都市",
    cityTokyo = "東京",
    cityOsaka = "大阪",
    cityKyoto = "京都",
    cityYokohama = "横浜",
    cityNagoya = "名古屋",
    cityFukuoka = "福岡",
    cityOther = "その他"
)

val LocalStrings = staticCompositionLocalOf { EnStrings }

val LocalTextColor = staticCompositionLocalOf { androidx.compose.ui.graphics.Color.White }
