package com.example.suicareader.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage { EN, ZH, JA }

data class AppStrings(
    val appName: String,
    val dashboardTitle: String,
    val settingsTitle: String,
    val darkTheme: String,
    val darkThemeDesc: String,
    val language: String,
    val languageDesc: String,
    val openSource: String,
    val openSourceDesc: String,
    val addManualEntry: String,
    val typeFare: String,
    val typeCharge: String,
    val amountInput: String,
    val selectInStation: String,
    val selectOutStation: String,
    val cancel: String,
    val save: String,
    val searchStation: String,
    val searchPlaceholder: String,
    val noResults: String,
    val fareSubway: String,
    val chargeTopUp: String,
    val busFare: String,
    val purchase: String,
    val locationPrefix: String,
    val busRoutePrefix: String,
    val terminalPrefix: String,
    val inPrefix: String,
    val outPrefix: String,
    val currentBalance: String,
    val editCard: String,
    val renameCard: String,
    val deleteCard: String,
    val renameDialogTitle: String,
    val cardNameLabel: String,
    val cardNumberLabel: String,
    val cardNumberPlaceholder: String,
    val tripHistory: String,
    val balanceLabel: String
)

val EnStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "My Cards",
    settingsTitle = "Settings",
    darkTheme = "Dark Theme",
    darkThemeDesc = "Toggle liquid glass background mode",
    language = "Language",
    languageDesc = "System Default / Selected",
    openSource = "Open Source",
    openSourceDesc = "View GitHub Repository",
    addManualEntry = "Add Manual Entry",
    typeFare = "Fare",
    typeCharge = "Charge",
    amountInput = "Amount (¥)",
    selectInStation = "Select In-Station / Location",
    selectOutStation = "Select Out-Station",
    cancel = "Cancel",
    save = "Save",
    searchStation = "Search Station",
    searchPlaceholder = "Enter station name...",
    noResults = "No results found.",
    fareSubway = "Fare (Subway)",
    chargeTopUp = "Charge (Top-up)",
    busFare = "Bus Fare",
    purchase = "Purchase (Vending/Store)",
    locationPrefix = "Location:",
    busRoutePrefix = "Bus Route/ID:",
    terminalPrefix = "Terminal:",
    inPrefix = "In:",
    outPrefix = "Out:",
    currentBalance = "Current Balance",
    editCard = "Edit Card",
    renameCard = "Rename",
    deleteCard = "Delete",
    renameDialogTitle = "Rename Card",
    cardNameLabel = "Card Name",
    cardNumberLabel = "Card Number (Last 4 digits)",
    cardNumberPlaceholder = "Optional",
    tripHistory = "Trip History",
    balanceLabel = "Balance"
)

val ZhStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "我的卡片",
    settingsTitle = "设置",
    darkTheme = "深色模式",
    darkThemeDesc = "切换深色液态玻璃背景",
    language = "语言",
    languageDesc = "系统默认 / 已选择",
    openSource = "开源项目",
    openSourceDesc = "查看 GitHub 仓库",
    addManualEntry = "手动记账",
    typeFare = "乘车/消费",
    typeCharge = "充值",
    amountInput = "金额 (¥)",
    selectInStation = "选择进站 / 发生地",
    selectOutStation = "选择出站",
    cancel = "取消",
    save = "保存",
    searchStation = "搜索车站",
    searchPlaceholder = "输入车站拼音或汉字...",
    noResults = "未找到结果",
    fareSubway = "地铁/电车",
    chargeTopUp = "充值",
    busFare = "公交",
    purchase = "购物/自动售货机",
    locationPrefix = "地点:",
    busRoutePrefix = "公交线路:",
    terminalPrefix = "终端:",
    inPrefix = "进:",
    outPrefix = "出:",
    currentBalance = "当前余额",
    editCard = "编辑卡片",
    renameCard = "重命名",
    deleteCard = "删除",
    renameDialogTitle = "修改卡片信息",
    cardNameLabel = "卡片名称",
    cardNumberLabel = "卡号尾数 (后四位)",
    cardNumberPlaceholder = "选填",
    tripHistory = "行程记录",
    balanceLabel = "余额"
)

val JaStrings = AppStrings(
    appName = "Suica Reader",
    dashboardTitle = "マイカード",
    settingsTitle = "設定",
    darkTheme = "ダークモード",
    darkThemeDesc = "液体ガラスの背景を切り替え",
    language = "言語",
    languageDesc = "システムデフォルト / 選択済み",
    openSource = "オープンソース",
    openSourceDesc = "GitHub リポジトリを表示",
    addManualEntry = "手動入力",
    typeFare = "運賃/支払い",
    typeCharge = "チャージ",
    amountInput = "金額 (¥)",
    selectInStation = "乗車駅 / 場所を選択",
    selectOutStation = "降車駅を選択",
    cancel = "キャンセル",
    save = "保存",
    searchStation = "駅を検索",
    searchPlaceholder = "駅名を入力...",
    noResults = "結果が見つかりません",
    fareSubway = "運賃 (電車)",
    chargeTopUp = "チャージ",
    busFare = "バス運賃",
    purchase = "物販",
    locationPrefix = "場所:",
    busRoutePrefix = "バス路線:",
    terminalPrefix = "端末:",
    inPrefix = "入:",
    outPrefix = "出:",
    currentBalance = "残高",
    editCard = "カードを編集",
    renameCard = "名前を変更",
    deleteCard = "削除",
    renameDialogTitle = "カード情報の編集",
    cardNameLabel = "カード名",
    cardNumberLabel = "カード番号 (下4桁)",
    cardNumberPlaceholder = "任意",
    tripHistory = "利用履歴",
    balanceLabel = "残高"
)

val LocalStrings = staticCompositionLocalOf { EnStrings }

val LocalTextColor = staticCompositionLocalOf { androidx.compose.ui.graphics.Color.White }
